spring:
  datasource:
    url: jdbc:postgresql://localhost:5402/ms_email_ms
    username: postgres_email_pb
    password: postgres_password

  rabbitmq:
    addresses: possum.lmq.cloudamqp.com
    username: gttcxdpc
    password: 4-6zqXVQe9IlT0EkjdzVq4WTzKwbgWIH
    virtual-host: gttcxdpc

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL-NAME}
    password: ${EMAIL-PASSWORD}
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                  enable: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: amqps://duck.lmq.cloudamqp.com
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: pofhowkh

  flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
      smtp:
      auth: true
      starttls:
      enable: true


  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
